### ISSUE TITLE
Check APrime documentation

### ISSUE THREAD

**Issue by jmmans** [tomeichlersmith/G4DarkBreM#8]
Is the particle id here standarized?  If so, perhaps clarify in comment.

https://github.com/tomeichlersmith/G4DarkBreM/blob/c8a9ccf2018f84bd0a8f824f352b8ef2383b0c44/src/G4DarkBreM/G4APrime.cxx#L33

Comments on each parameter value might be useful (Work for Mike R).

**Comment by tomeichlersmith** [comment]
This number is not standard and so I have updated the code to let the user configure it if they so wish. The new default is `62` rather than `622` in order to choose a number from the available list of "one-of-a-kind" BSM particles as given by [PDG ID schme](https://pdg.lbl.gov/2007/reviews/montecarlorpp.pdf).

Resolved by bdd16da8afeaa9c26f9b2991fcca829dc9d50a8f
